version: '3.8'

services:

  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    entrypoint: ['/usr/src/app/entrypoint.sh']
    tty: true
    volumes:
      - './backend:/usr/src/app'
    ports:
      - 5004:5000
    depends_on:
      - api-db

  api-db:
    build:
      context: ./db
      dockerfile: Dockerfile
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  client:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - 3007:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - api